#ifndef GRAPH_H
#define GRAPH_H

#include <stdlib.h>
#include <stdio.h>
#include <stdbool.h>
#include <time.h>
#include <string.h>

// A node in the adjacency list representation of the graph
typedef struct AdjacencyListNode {
    struct AdjacencyListNode* next;
    int node;
    double weight;
} AdjacencyListNode;

// The graph represented by an adjacency list
// This graph has a locality radius which is used for the generation of random graphs. It determines how far two connected nodes are allowed to be.
typedef struct Graph {
    int vertexAmount;
    bool directed;
    double localityRadius;
    AdjacencyListNode** adjacencyList;
} Graph;

// Creates and returns a directed/undirected graph with the given vertices amount and locality radius.
Graph* create_graph(int amountOfVertices, double localityRadius, bool directed);

// Creates a node to be used in an adjacency list.
AdjacencyListNode* create_node(int node);

// Adds a weighted edge between the given nodes 
void add_edge(Graph* graph, int source, int target, double weight);

// Checks whether a connection exists between the given nodes
bool edge_exists(Graph* graph, int source, int target);

// Shuffles the list of vertices. Essentialy a normal list shuffle
void shuffle_vertices(int* vertices, int length);

// Connects a given graph in a lattice form, which is: each node n is connected with the n+"offset" neighbour.
// If n+"offset" is greater than the amount of nodes, it loops back to the beginning
void connect_lattice(Graph* graph, int* vertices, int offset, int* edgeCounter, int maxEdges);

// Generates a random connected graph using a variant of the Watts-Strogatz algorithm.
void load_random_connected_graph(Graph* graph, int edgeAmount, int degree);

// Generates a random connected graph the same way a ```load_random_connected_graph``` would, but gives each node a coordinate.
// Used when evaluating the performance of A* as its heuristic requires topological information
long** load_random_graph_coords(Graph* graph, int edgeAmount, int degree);

// UNUSED
// Generates a random graph using the Erdos-Renyi model, unused as it showed inferior results to the Watts-Strogatz method.
void load_erdos_renyi_model_graph(Graph* graph, int edgeAmount, double prob);

// UNUSED
// Also generates a random graph using the Erdos-Renyi model, but tries to maintain small-world properties that the Watts-Strogatz algorithm adds
void load_realistic_random_graph(Graph* graph, int edgeAmount);

// Loads a small graph generated by AI, handy for manual checking
void load_generated_graph(Graph* graph);

// UNUSED
// First prototype of making a random graph with topological meaning.
// Loads a graph by placing the vertices in a grid
void load_grid_graph(Graph* graph, int rows, double prob);

// Saves the state of a graph to a csv file
void save_graph_to_csv(Graph* graph, char fileName[]);

// Loads the state of a graph from a csv file
void load_graph_from_csv(Graph* graph, char fileName[]);

// Loads a graph state from a Stanford file.
void load_graph_stanford(Graph* graph, char fileName[]);

// Loads a graph state and coordinates from a DIMACS file
long** load_graph_dimacs(Graph* graph, char dataFileName[], char coordFileName[]);

// Returns a list of all degrees in a graph.
float* get_degrees(Graph* graph);

// Returns a reversed/transposed graph in which all directed edges point in the opposite direction
Graph* reverse_graph(Graph* graph);

// Prints the graph
void print_graph(Graph* graph);

// Prints the graph in a readable format
void print_graph_descriptive(Graph* graph);

// Frees the resources used by the graph
void free_graph(Graph* graph);

#endif